const mongoose = require('mongoose')

// Simple connection without ES6 imports for Node.js script
const MONGODB_URI = process.env.MONGODB_URI || 'mongodb://localhost:27017/sonnas-restaurant'

// Define schemas directly in the script
const UserSchema = new mongoose.Schema({
  name: { type: String, required: true },
  email: { type: String, required: true, unique: true },
  password: { type: String, required: true },
  role: { type: String, enum: ['customer', 'admin'], default: 'customer' },
  phone: String,
  address: {
    street: String,
    city: String,
    state: String,
    zipCode: String,
  },
}, { timestamps: true })

const MenuItemSchema = new mongoose.Schema({
  name: { type: String, required: true },
  description: { type: String, required: true },
  price: { type: Number, required: true },
  category: { type: String, required: true, enum: ['Small Bites', 'Pizza', 'House Specials', 'Drinks'] },
  image: { type: String, required: true },
  isAvailable: { type: Boolean, default: true },
  ingredients: [String],
  allergens: [String],
  nutritionalInfo: {
    calories: Number,
    protein: Number,
    carbs: Number,
    fat: Number,
  },
  preparationTime: { type: Number, required: true },
  isPopular: { type: Boolean, default: false },
  rating: { type: Number, default: 0, min: 0, max: 5 },
  reviews: { type: Number, default: 0 },
}, { timestamps: true })

const User = mongoose.model('User', UserSchema)
const MenuItem = mongoose.model('MenuItem', MenuItemSchema)

const sampleMenuItems = [
  // Small Bites
  {
    name: 'Korean Bun',
    description: 'Traditional Korean-style steamed bun',
    price: 160,
    category: 'Small Bites',
    image: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80',
    ingredients: ['Korean flour', 'Yeast', 'Sesame'],
    allergens: ['Gluten', 'Sesame'],
    nutritionalInfo: { calories: 180, protein: 6, carbs: 32, fat: 3 },
    preparationTime: 15,
    isPopular: false,
    rating: 4.5,
    reviews: 45,
    isAvailable: true,
  },
  {
    name: 'Chilli Korean Bun',
    description: 'Spicy Korean-style steamed bun with chili',
    price: 170,
    category: 'Small Bites',
    image: 'https://images.unsplash.com/photo-1551218808-94e220e084d2?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80',
    ingredients: ['Korean flour', 'Chili', 'Spices'],
    allergens: ['Gluten'],
    nutritionalInfo: { calories: 190, protein: 6, carbs: 33, fat: 4 },
    preparationTime: 15,
    isPopular: false,
    rating: 4.6,
    reviews: 52,
    isAvailable: true,
  },
  {
    name: 'Potato Wedges',
    description: 'Crispy golden potato wedges',
    price: 120,
    category: 'Small Bites',
    image: 'https://images.unsplash.com/photo-1541592106381-b31e9677c0e5?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80',
    ingredients: ['Potatoes', 'Spices', 'Oil'],
    allergens: [],
    nutritionalInfo: { calories: 250, protein: 4, carbs: 35, fat: 12 },
    preparationTime: 12,
    isPopular: false,
    rating: 4.3,
    reviews: 38,
    isAvailable: true,
  },
  {
    name: 'Chilli Garlic Wedges',
    description: 'Spicy potato wedges with chili and garlic',
    price: 150,
    category: 'Small Bites',
    image: 'https://images.unsplash.com/photo-1608767221051-2b9c18319fbc?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80',
    ingredients: ['Potatoes', 'Chili', 'Garlic', 'Spices'],
    allergens: [],
    nutritionalInfo: { calories: 270, protein: 4, carbs: 36, fat: 14 },
    preparationTime: 12,
    isPopular: false,
    rating: 4.4,
    reviews: 42,
    isAvailable: true,
  },
  {
    name: 'Cauliflower Florets',
    description: 'Crispy fried cauliflower florets',
    price: 260,
    category: 'Small Bites',
    image: 'https://images.unsplash.com/photo-1609501676725-7186f932a4b0?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80',
    ingredients: ['Cauliflower', 'Spices', 'Batter'],
    allergens: ['Gluten'],
    nutritionalInfo: { calories: 220, protein: 8, carbs: 28, fat: 10 },
    preparationTime: 15,
    isPopular: true,
    rating: 4.7,
    reviews: 78,
    isAvailable: true,
  },
  {
    name: 'Sliders',
    description: 'Mini burgers perfect for sharing',
    price: 185,
    category: 'Small Bites',
    image: 'https://images.unsplash.com/photo-1571091718767-18b5b1457add?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80',
    ingredients: ['Mini bun', 'Patty', 'Cheese', 'Lettuce'],
    allergens: ['Gluten', 'Dairy'],
    nutritionalInfo: { calories: 320, protein: 18, carbs: 25, fat: 16 },
    preparationTime: 10,
    isPopular: true,
    rating: 4.8,
    reviews: 95,
    isAvailable: true,
  },
  {
    name: 'Sliders Appetizers',
    description: 'Mini burgers (2 sliders)',
    price: 260,
    category: 'Small Bites',
    image: 'https://images.unsplash.com/photo-1586816001966-79b736744398?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80',
    ingredients: ['Mini bun', 'Beef patty', 'Cheese'],
    allergens: ['Gluten', 'Dairy'],
    nutritionalInfo: { calories: 420, protein: 22, carbs: 28, fat: 24 },
    preparationTime: 10,
    isPopular: true,
    rating: 4.9,
    reviews: 89,
    isAvailable: true,
  },
  {
    name: 'Paneer Appetizers',
    description: 'Delicious paneer appetizers',
    price: 260,
    category: 'Small Bites',
    image: 'https://images.unsplash.com/photo-1631452180539-96aca7d48617?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80',
    ingredients: ['Paneer', 'Spices', 'Herbs'],
    allergens: ['Dairy'],
    nutritionalInfo: { calories: 280, protein: 18, carbs: 8, fat: 20 },
    preparationTime: 15,
    isPopular: false,
    rating: 4.6,
    reviews: 67,
    isAvailable: true,
  },

  // Pizza - Hand Rolled Thin Crust
  {
    name: 'Margherita Pizza',
    description: 'Hand Rolled Thin Crust pizza with fresh mozzarella and basil',
    price: 230,
    category: 'Pizza',
    image: 'https://images.unsplash.com/photo-1604382354936-07c5d9983bd3?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80',
    ingredients: ['Thin crust', 'Tomato sauce', 'Mozzarella', 'Basil'],
    allergens: ['Gluten', 'Dairy'],
    nutritionalInfo: { calories: 280, protein: 12, carbs: 35, fat: 10 },
    preparationTime: 15,
    isPopular: true,
    rating: 4.8,
    reviews: 98,
    isAvailable: true,
  },
  {
    name: 'Mexican Pizza',
    description: 'Loaded Vegetables pizza with Mexican flavors',
    price: 270,
    category: 'Pizza',
    image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80',
    ingredients: ['Thin crust', 'Vegetables', 'Mexican spices', 'Cheese'],
    allergens: ['Gluten', 'Dairy'],
    nutritionalInfo: { calories: 320, protein: 14, carbs: 38, fat: 14 },
    preparationTime: 18,
    isPopular: false,
    rating: 4.7,
    reviews: 76,
    isAvailable: true,
  },
  {
    name: 'Fantasy Pizza',
    description: 'Onions, Bellpeppers, Paneer, Coriander, and Oregano',
    price: 270,
    category: 'Pizza',
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80',
    ingredients: ['Onions', 'Bell peppers', 'Paneer', 'Coriander', 'Oregano'],
    allergens: ['Gluten', 'Dairy'],
    nutritionalInfo: { calories: 350, protein: 16, carbs: 38, fat: 16 },
    preparationTime: 20,
    isPopular: true,
    rating: 4.6,
    reviews: 134,
    isAvailable: true,
  },
  {
    name: 'Cleilia Pizza',
    description: 'Mushroom, Pickled Onion, Chilli Garlic Oil, Basil',
    price: 290,
    category: 'Pizza',
    image: 'https://images.unsplash.com/photo-1571997478779-2adcbbe9ab2f?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80',
    ingredients: ['Mushroom', 'Pickled Onion', 'Chilli Garlic Oil', 'Basil'],
    allergens: ['Gluten', 'Dairy'],
    nutritionalInfo: { calories: 310, protein: 13, carbs: 36, fat: 15 },
    preparationTime: 18,
    isPopular: false,
    rating: 4.8,
    reviews: 89,
    isAvailable: true,
  },
  {
    name: 'Neapolitan Pizza',
    description: 'Onions, Bellpeppers, Black Olives, Jalepeno, Chilli Garlic Oil',
    price: 290,
    category: 'Pizza',
    image: 'https://images.unsplash.com/photo-1595708684082-a173bb3a06c5?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80',
    ingredients: ['Onions', 'Bellpeppers', 'Black Olives', 'Jalepeno', 'Chilli Garlic Oil'],
    allergens: ['Gluten', 'Dairy'],
    nutritionalInfo: { calories: 330, protein: 14, carbs: 39, fat: 16 },
    preparationTime: 20,
    isPopular: true,
    rating: 4.9,
    reviews: 156,
    isAvailable: true,
  },
  {
    name: 'Rustic Pizza',
    description: 'Onions, Garlic Oil, Spinach, Oregano',
    price: 290,
    category: 'Pizza',
    image: 'https://images.unsplash.com/photo-1589834390005-5d4fb9bf3d32?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80',
    ingredients: ['Onions', 'Garlic Oil', 'Spinach', 'Oregano'],
    allergens: ['Gluten', 'Dairy'],
    nutritionalInfo: { calories: 300, protein: 12, carbs: 37, fat: 14 },
    preparationTime: 18,
    isPopular: false,
    rating: 4.7,
    reviews: 112,
    isAvailable: true,
  },

  // House Specials
  {
    name: 'Amritsari Chole with House Baked Kulche',
    description: 'Homemade Punjabi style Chhole filled with love',
    price: 240,
    category: 'House Specials',
    image: 'https://images.unsplash.com/photo-1606491956689-2ea866880c84?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80',
    ingredients: ['Chickpeas', 'Kulcha bread', 'Punjabi spices'],
    allergens: ['Gluten'],
    nutritionalInfo: { calories: 380, protein: 16, carbs: 58, fat: 8 },
    preparationTime: 25,
    isPopular: true,
    rating: 4.9,
    reviews: 123,
    isAvailable: true,
  },
  {
    name: 'Khao Suey',
    description: 'Coconut based Curry filled with noodles and loads of condiments',
    price: 280,
    category: 'House Specials',
    image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80',
    ingredients: ['Coconut curry', 'Noodles', 'Various condiments'],
    allergens: ['Gluten'],
    nutritionalInfo: { calories: 420, protein: 14, carbs: 52, fat: 18 },
    preparationTime: 20,
    isPopular: true,
    rating: 4.8,
    reviews: 145,
    isAvailable: true,
  },
  {
    name: 'Paneer Tikka/Butter Masala with Rice or Kulcha',
    description: 'Creamy Paneer Tikay (spicy) or Butter (sweet) Masala served with Rice or Kulcha (your choice)',
    price: 295,
    category: 'House Specials',
    image: 'https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80',
    ingredients: ['Paneer', 'Tomato gravy', 'Rice/Kulcha'],
    allergens: ['Dairy', 'Gluten'],
    nutritionalInfo: { calories: 450, protein: 22, carbs: 45, fat: 22 },
    preparationTime: 25,
    isPopular: true,
    rating: 4.9,
    reviews: 203,
    isAvailable: true,
  },
  {
    name: 'Dal Makhni with Rice or Kulcha',
    description: 'Creamy homemade Kail Dal served with Rice or Kulcha (your choice)',
    price: 295,
    category: 'House Specials',
    image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80',
    ingredients: ['Black lentils', 'Cream', 'Rice/Kulcha'],
    allergens: ['Dairy', 'Gluten'],
    nutritionalInfo: { calories: 380, protein: 18, carbs: 42, fat: 16 },
    preparationTime: 30,
    isPopular: true,
    rating: 4.8,
    reviews: 167,
    isAvailable: true,
  },
  {
    name: 'Paneer Tikka',
    description: 'Grilled paneer with aromatic spices',
    price: 290,
    category: 'House Specials',
    image: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80',
    ingredients: ['Paneer', 'Spices', 'Yogurt marinade'],
    allergens: ['Dairy'],
    nutritionalInfo: { calories: 320, protein: 20, carbs: 12, fat: 22 },
    preparationTime: 20,
    isPopular: false,
    rating: 4.7,
    reviews: 89,
    isAvailable: true,
  },
  {
    name: 'Customise Your Own Pizza',
    description: 'Create your perfect pizza with your choice of toppings',
    price: 250,
    category: 'House Specials',
    image: 'https://images.unsplash.com/photo-1594007654729-407eedc4be65?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80',
    ingredients: ['Pizza base', 'Choice of toppings'],
    allergens: ['Gluten', 'Dairy'],
    nutritionalInfo: { calories: 350, protein: 15, carbs: 40, fat: 16 },
    preparationTime: 20,
    isPopular: true,
    rating: 4.8,
    reviews: 234,
    isAvailable: true,
  },

  // Drinks
  {
    name: 'Iced Teas',
    description: 'Refreshing iced tea',
    price: 120,
    category: 'Drinks',
    image: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80',
    ingredients: ['Tea', 'Ice', 'Sugar'],
    allergens: [],
    nutritionalInfo: { calories: 60, protein: 0, carbs: 15, fat: 0 },
    preparationTime: 3,
    isPopular: false,
    rating: 4.4,
    reviews: 56,
    isAvailable: true,
  },
  {
    name: 'Peach/Lemon/Blueberry',
    description: 'Flavored refreshing drinks',
    price: 130,
    category: 'Drinks',
    image: 'https://images.unsplash.com/photo-1544145945-f90425340c7e?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80',
    ingredients: ['Fruit flavors', 'Water', 'Sugar'],
    allergens: [],
    nutritionalInfo: { calories: 80, protein: 0, carbs: 20, fat: 0 },
    preparationTime: 4,
    isPopular: false,
    rating: 4.5,
    reviews: 67,
    isAvailable: true,
  },
  {
    name: 'Cucumber Lemonade',
    description: 'Fresh cucumber and lemon drink',
    price: 140,
    category: 'Drinks',
    image: 'https://images.unsplash.com/photo-1571068316344-75bc76f77890?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80',
    ingredients: ['Cucumber', 'Lemon', 'Mint'],
    allergens: [],
    nutritionalInfo: { calories: 45, protein: 1, carbs: 11, fat: 0 },
    preparationTime: 5,
    isPopular: false,
    rating: 4.6,
    reviews: 76,
    isAvailable: true,
  },
  {
    name: 'Mojito',
    description: 'Classic refreshing mojito',
    price: 140,
    category: 'Drinks',
    image: 'https://images.unsplash.com/photo-1551538827-9c037cb4f32a?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80',
    ingredients: ['Mint', 'Lime', 'Soda water'],
    allergens: [],
    nutritionalInfo: { calories: 35, protein: 0, carbs: 9, fat: 0 },
    preparationTime: 4,
    isPopular: false,
    rating: 4.7,
    reviews: 92,
    isAvailable: true,
  },
  {
    name: 'Cold Coffee',
    description: 'Chilled coffee drink',
    price: 120,
    category: 'Drinks',
    image: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80',
    ingredients: ['Coffee', 'Milk', 'Ice', 'Sugar'],
    allergens: ['Dairy'],
    nutritionalInfo: { calories: 150, protein: 4, carbs: 20, fat: 6 },
    preparationTime: 5,
    isPopular: false,
    rating: 4.5,
    reviews: 78,
    isAvailable: true,
  },
  {
    name: 'Milkshakes',
    description: 'KitKat/Vanilla/Strawberry/Chocolate flavored milkshakes',
    price: 160,
    category: 'Drinks',
    image: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=80',
    ingredients: ['Milk', 'Ice cream', 'Flavoring'],
    allergens: ['Dairy', 'Gluten'],
    nutritionalInfo: { calories: 320, protein: 8, carbs: 42, fat: 14 },
    preparationTime: 5,
    isPopular: true,
    rating: 4.8,
    reviews: 189,
    isAvailable: true,
  }
]

const sampleUsers = [
  {
    name: 'Admin User',
    email: 'admin@sonnas.com',
    password: '$2a$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewdBPfKwqzrj6M0m', // hashed 'admin123'
    role: 'admin',
    phone: '(555) 123-4567',
    address: {
      street: '123 Restaurant Ave',
      city: 'Culinary City',
      state: 'CA',
      zipCode: '90210',
    },
  },
  {
    name: 'John Doe',
    email: 'john.doe@example.com',
    password: '$2a$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewdBPfKwqzrj6M0m', // hashed 'password123'
    role: 'customer',
    phone: '(555) 987-6543',
    address: {
      street: '456 Customer St',
      city: 'Food City',
      state: 'CA',
      zipCode: '90211',
    },
  }
]

async function seedDatabase() {
  try {
    // Connect to MongoDB
    await mongoose.connect(MONGODB_URI)
    console.log('Connected to MongoDB')

    // Clear existing data
    await User.deleteMany({})
    await MenuItem.deleteMany({})
    console.log('Cleared existing data')

    // Insert sample data
    await User.insertMany(sampleUsers)
    console.log('Inserted sample users')

    await MenuItem.insertMany(sampleMenuItems)
    console.log('Inserted sample menu items')

    console.log('Database seeded successfully!')
    console.log(`Inserted ${sampleUsers.length} users and ${sampleMenuItems.length} menu items`)

  } catch (error) {
    console.error('Error seeding database:', error)
  } finally {
    await mongoose.disconnect()
    console.log('Disconnected from MongoDB')
  }
}

// Run the seed function
seedDatabase()
